#!/bin/sh
total=$(($2 + $3))
statefile=$HOME/.mutt/$1/state
if [ $total -eq 0 ]
then
    if [ -f $statefile ]
    then
        rm $HOME/.mutt/$1/state 2>/dev/null
        nohup sh $HOME/.dwm.update 1>/dev/null 2>&1 &
    fi
else
    oldtotal=0
    if [ -f $statefile ]
    then
        oldtotal=$(cat $statefile)
    fi
    if [ $total -ne $oldtotal ]
    then
        echo $total > $HOME/.mutt/$1/state
        nohup sh $HOME/.dwm.update 1>/dev/null 2>&1 &
        if [ $total -gt $oldtotal ]
        then
            echo -e "$1\n$total unread messages" | osd_cat -f "-misc-fixed-bold-r-normal--15-140-75-75-c-90-*-*" -l100 -o 30 -s 1 -c green -
        fi
    fi
fi

echo $4
