#!/bin/sh
if [ $screenrc"x" = "x" ]
then
    screenrc=$(mktemp)
    cp $HOME/.screenrc $screenrc
    should_start=yes
fi

echo "screen $HOME/.mutt/imapsync" >> $screenrc
echo title imapsync >> $screenrc

for x in $(find .mutt/*/ -maxdepth 2 -name muttrc -type f|sort)
do
    echo screen mutt -F $x>>$screenrc
    name=`echo $x|grep -o "[^/]*/muttrc$" | grep -o "^[^/]*"`
    echo title mail@$name>>$screenrc
done

if [ $should_start"x" = "yesx" ]
then
    /usr/bin/screen -c $screenrc
    rm -f $screenrc
fi

