#!/bin/sh -x
PORTAGE_LOOP=portage.loop
umount /usr/portage
rm $PORTAGE_LOOP
set -e
truncate -s 1024M $PORTAGE_LOOP
mke2fs -b 1024 -I 128 -N 200000 -m 0 -E resize=2048000 -O "^ext_attr" -v $PORTAGE_LOOP
tune2fs -o "^acl,^user_xattr" $PORTAGE_LOOP
mount /usr/portage
DIRSTDIR=/tmp emerge-webrsync
emerge --sync
