#!/bin/sh
killall skype
killall irrsi
for x in ~/.mcabber/*/mcabber.fifo
do
    echo "/disconnect" > $x
done

while ! slock; do :; done;

for x in ~/.mcabber/*/mcabber.fifo
do
    echo "/connect" > $x
done

nohup skype >/dev/null 2>&1 &

