#! /bin/sh
account=$1
event=$2
arg1=$3
arg2=$4
filename=$5
# Note that the 4th argument is only provided for incoming messages
# and when 'event_log_files' is set.

if [ $event = "MSG" ]; then
    case "$arg1" in
        IN)
            # Incoming message from buddy $arg2
            cat - $filename <<< "$arg2" | osd_cat -A right -f "-misc-fixed-bold-r-normal--15-140-75-75-c-90-*-*" -l100 -o 30 -s 1 -c green -
            ;;
        MUC)
            # Incoming message from buddy $arg2
            cat - $filename <<< "$arg2" | osd_cat -A right -f "-misc-fixed-bold-r-normal--15-140-75-75-c-90-*-*" -l100 -o 30 -s 1 -c green -
            ;;
    esac
    if [ -n "$filename" -a -f "$filename" ]; then
        # We could process filename here...
        /bin/rm $filename
    fi
elif [ $event = "UNREAD" ]; then
    # $arg1 contains 4 numbers separated with space chars:
    # Nr of unread buffers, nr of unread buffers with attention sign,
    # nr of MUC unread buffers, nr of MUC unread buffers with attention sign.
    read count other <<< $arg1
    if [ $count -eq 0 ]
    then
        rm $HOME/.mcabber/$account/state 2>/dev/null
    else
        echo $count >$HOME/.mcabber/$account/state
    fi
    sh $HOME/.dwm.update
fi
