#! /bin/sh
event=$1
arg1=$2
arg2=$3
filename=$4
# Note that the 4th argument is only provided for incoming messages
# and when 'event_log_files' is set.

if [ $event = "MSG" ]; then
    case "$arg1" in
        IN)
            # Incoming message from buddy $arg2
            str="\"<span color='#3333CC'>$arg2</span>: \" .. io.open('$filename','r'):read('*all')"
            command="naughty.notify({text=$str,timeout=3,screen=mouse.screen})"
            echo $command|awesome-client
            if [ -n "$filename" -a -f "$filename" ]; then
                # We could process filename here...
                /bin/rm $filename
            fi
            ;;
        MUC)
            if [ -n "$filename" -a -f "$filename" ]; then
                # We could process filename here...
                /bin/rm $filename
            fi
            ;;
    esac
elif [ $event = "UNREAD" ]; then
    # $arg1 contains 4 numbers separated with space chars:
    # Nr of unread buffers, nr of unread buffers with attention sign,
    # nr of MUC unread buffers, nr of MUC unread buffers with attention sign.
    echo -ne "\ek"$arg1"\e\\"
fi
